name: auction_fire
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.4.0
  firebase_database: ^10.1.0
  firebase_core: ^2.7.1
  firebase_storage: ^11.0.14
  firebase_auth: ^4.2.10
  cloud_firestore: ^4.6.0
  fluttertoast: ^8.2.1
  #google_sign_in: ^6.1.0
  wc_form_validators: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets: 
    - images/apple_watch.png
    - images/t_shirt.png
