name: auction_fire
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.4.0
  firebase_database: ^10.1.0
  firebase_core: ^2.7.1
  firebase_storage: ^11.0.14
  firebase_auth: ^4.2.10
  cloud_firestore: ^4.6.0
  fluttertoast: ^8.2.1
  google_sign_in: 
  wc_form_validators: ^1.0.0
  sizer:
  flutter_admin_scaffold: ^1.2.0
  image_picker: ^1.0.2
  uuid: ^3.0.7
  permission_handler: ^10.4.3
  file_picker: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets: 
    - images/apple_watch.png
    - images/t_shirt.png
